### ISSUE TITLE
Loss of adsl connection

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#41]
Hello,

If I have an ADSL disconnection, Pyze no longer updates the information as soon as the ADSL has returned. The actions don't work too. I have to do a Hassio reboot for this to work.
Would there be a possible refresh solution through automation?

Thank you

**Comment by epenet** [comment]
Hi @JeedHome44 ,

Can you update to [v3.0.0](https://github.com/epenet/hassRenaultZE/releases/tag/v3.0.0) and see if that is still an issue?

**Comment by JeedHome44** [comment]
Hi,

My lan is Now with OpenMPTCPRouteur.
So, I have always connection.

I will try this 3.0 as soon as possible. 😉

**Comment by JeedHome44** [comment]
Hi,
what does this version 3.0 bring?

**Comment by epenet** [comment]
Mainly, it is configured through the UI
Secondly, all the results are full sensors now and there is no need to use attributes

**Comment by JeedHome44** [comment]
I've never needed to use attributes personally.  I send all the information by HTTP request to Jeedom.  and it is Jeedom who activates each action by a script on Home Assistant 😄

**Comment by epenet** [comment]
Can we close this issue then?

**Comment by JeedHome44** [comment]
I didn't update because I don't understand what all these changes are all about.  it allows to continue to work even if the connection is lost?

**Comment by epenet** [comment]
Your original issue doesn't have enough information to make an investigation.

If you wish to investigate it more, then you need to upgrade and try to replicate your issue.
If you do not wish to investigate it more, then just close this issue.

**Comment by epenet** [comment]
I think I managed to replicate this... it occurs if the internet is not available during startup.
We should try to add a retry if it fails during startup.

**Comment by JeedHome44** [comment]
Hello,

that would be great if you can add a new attempt if the first one fails!  😉

**Comment by epenet** [comment]
If anyone is wanting to look at this, the idea is to raise `ConfigEntryNotReady` during the initialisation (inside `__init__.py > async_setup_entry`)
The issue will be to distinguish "internet errors" from "failed credentials" so might need some changes to PyZE library

**Comment by JeedHome44** [comment]
Hello,

Is it possible to create a service that allows you to restart synchronization manually?
That would allow it to be automatically restarted in an automation as soon as my Zoe leaves or arrives from the house for example.
This would temporarily resolve this problem.

Thank you

**Comment by JeedHome44** [comment]
can we use hassio.addon_restart with an automation?

if yes? how please?

**Comment by epenet** [comment]
@JeedHome44 [release v3.0.2](https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.2) has updated the startup routine, and implements ConfigEntryNotReady so HA should automatically re-attempt if the failure occurs at startup ?

If not, then please provide some **logs/traces/anything** that helps us understand what the issue is.

**Comment by JeedHome44** [comment]
Oh thank you!
I will test that 😉

**Comment by JeedHome44** [comment]
I downloaded the renault file.
I restarted Hassio but I cannot find "Renault" in the list of integrations.
Why?

**Comment by JeedHome44** [comment]
Is there a minimum version of Home assistant to have?

**Comment by epenet** [comment]
Tested again v118 - haven't tested against earlier versions

**Comment by JeedHome44** [comment]
I have Home Assistant Core  0.105.3 and HassOS 5.2
I have to update to 0.118.5?

**Comment by JeedHome44** [comment]
I do not understand.

I updated the Core. I was able to install the integration afterwards. It displayed the information well at the beginning and then it put this ...

Why?

**Comment by JeedHome44** [comment]
![Capture2](https://user-images.githubusercontent.com/41892950/101268834-3cbbd000-3768-11eb-9fa2-0f08223c4498.JPG)
![Capture](https://user-images.githubusercontent.com/41892950/101268835-3f1e2a00-3768-11eb-86ea-d9e14538b076.JPG)

**Comment by JeedHome44** [comment]
I hadn't disabled the sensor using PyZE and I think it was conflicting. It is working now.
But how do I adapt my scripts to activate the calendar, the preconditioning ... with this integration?
I had not yet updated 3.0

```
'1589190413353':
  alias: zoe40_ac_start_now_19
  sequence:
  - data:
      temperature: 19
    entity_id: sensor.zoe40
    service: renaultze.ac_start
'1589190456408':
  alias: zoe40_ac_cancel
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.ac_cancel
'1589190499937':
  alias: zoe40_charge_start
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.charge_start
'1589190593760':
  alias: zoe40_calendrier_on
  sequence:
  - data:
      charge_mode: schedule_mode
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode
'1589206784082':
  alias: zoe40_calendrier_off
  sequence:
  - data:
      charge_mode: always_charging
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode
'1589232410704':
  alias: zoe40_ac_start_now_22
  sequence:
  - data:
      temperature: 22
    entity_id: sensor.zoe40
    service: renaultze.ac_start
'1589476771733':
  alias: zoe40_calendrier_refresh
  sequence:
  - data:
      schedules:
        activated: true
        friday:
          duration: 240
          startTime: T02:00Z
        id: 1
        monday:
          duration: 240
          startTime: T02:00Z
        saturday:
          duration: 240
          startTime: T02:00Z
        sunday:
          duration: 240
          startTime: T02:00Z
        thursday:
          duration: 240
          startTime: T02:00Z
        tuesday:
          duration: 240
          startTime: T02:00Z
        wednesday:
          duration: 240
          startTime: T02:00Z
    entity_id: sensor.zoe40
    service: renaultze.charge_set_schedules
```

**Comment by JeedHome44** [comment]
For the calendar, is it possible to translate "SCHEDULE_MODE" by "Activated", "Activé" in french, and "ALWAYS_CHARGING" by "Deactivated", "Désactivé" in french?

![Capture](https://user-images.githubusercontent.com/41892950/101269529-fd917d00-376f-11eb-9921-9783fa57f9d4.JPG)

**Comment by JeedHome44** [comment]
Je viens de tester en changeant les scripts de cette façon, mais ça ne marche pas...

```
'1589190413353':
  alias: zoe40_ac_start_now_19
  sequence:
  - data:
      temperature: 19
      vin: vf1XXXXXXXXX
    service: renault.ac_start
'1589190456408':
  alias: zoe40_ac_cancel
  sequence:
  - data:
      vin: vf1XXXXXXXXX
    service: renault.ac_cancel
'1589190499937':
  alias: zoe40_charge_start
  sequence:
  - data:
      vin: vf1XXXXXXXXX
    service: renault.charge_start
'1589190593760':
  alias: zoe40_calendrier_on
  sequence:
  - data:
      charge_mode: schedule_mode
      vin: vf1XXXXXXXXX
    service: renault.charge_set_mode
'1589206784082':
  alias: zoe40_calendrier_off
  sequence:
  - data:
      charge_mode: always_charging
      vin: vf1XXXXXXXXX
    service: renault.charge_set_mode
'1589232410704':
  alias: zoe40_ac_start_now_22
  sequence:
  - data:
      temperature: 22
      vin: vf1XXXXXXXXX
    service: renault.ac_start
'1589476771733':
  alias: zoe40_calendrier_refresh
  sequence:
  - data:
      schedules:
        activated: true
        friday:
          duration: 240
          startTime: T02:00Z
        id: 1
        monday:
          duration: 240
          startTime: T02:00Z
        saturday:
          duration: 240
          startTime: T02:00Z
        sunday:
          duration: 240
          startTime: T02:00Z
        thursday:
          duration: 240
          startTime: T02:00Z
        tuesday:
          duration: 240
          startTime: T02:00Z
        wednesday:
          duration: 240
          startTime: T02:00Z
      vin: vf1XXXXXXXXX
    service: renault.charge_set_schedules
```

**Comment by epenet** [comment]
Can you send traces of the errors ?
Without traces, it's impossible to help you.

**Comment by JeedHome44** [comment]
how to get the logs? I have never done. thank you

**Comment by epenet** [comment]
I don't know the specifics of HassOS, but generally on HA-Core you have to add this to YAML:

```
logger:
  default: error
  logs:
    renault_api: debug
    custom_components.renault: debug
```
